# Generated by Django 3.2.3 on 2021-09-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolarSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orbit', models.BooleanField(default=True)),
                ('random', models.BooleanField(default=True)),
                ('border_size', models.IntegerField(default=40)),
                ('width', models.IntegerField(default=3000)),
                ('height', models.IntegerField(default=2000)),
                ('noise', models.FloatField(default=0.35)),
                ('white_star', models.IntegerField(default=400)),
                ('yellow_star', models.IntegerField(default=60)),
                ('blue_star', models.IntegerField(default=25)),
            ],
        ),
    ]
