# Generated by Django 3.2.3 on 2021-09-21 02:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solarsystem',
            old_name='blue_star',
            new_name='Blue Star Count',
        ),
        migrations.RenameField(
            model_name='solarsystem',
            old_name='height',
            new_name='Height of Image',
        ),
        migrations.RenameField(
            model_name='solarsystem',
            old_name='white_star',
            new_name='White Star Count in Background',
        ),
        migrations.RenameField(
            model_name='solarsystem',
            old_name='width',
            new_name='Width of Image',
        ),
        migrations.RenameField(
            model_name='solarsystem',
            old_name='yellow_star',
            new_name='Yellow Star Count in Background',
        ),
        migrations.RemoveField(
            model_name='solarsystem',
            name='border_size',
        ),
        migrations.RemoveField(
            model_name='solarsystem',
            name='noise',
        ),
        migrations.RemoveField(
            model_name='solarsystem',
            name='orbit',
        ),
        migrations.RemoveField(
            model_name='solarsystem',
            name='random',
        ),
        migrations.AddField(
            model_name='solarsystem',
            name='Border Size',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='solarsystem',
            name='Display',
            field=models.CharField(choices=[('orbit', 'Orbit'), ('line', 'Line')], default='Orbit', max_length=100),
        ),
        migrations.AddField(
            model_name='solarsystem',
            name='Nebula Background',
            field=models.CharField(choices=[('True', True), ('False', False)], default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='solarsystem',
            name='Noise/Texture of Final Image',
            field=models.FloatField(default=0.35, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='solarsystem',
            name='Randomize Placement?',
            field=models.CharField(choices=[('True', True), ('False', False)], default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='solarsystem',
            name='Rings',
            field=models.CharField(choices=[('True', True), ('False', False)], default=True, max_length=100),
        ),
    ]
