# Generated by Django 3.2.3 on 2021-09-23 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_auto_20210921_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solarsystem',
            name='Nebula Background',
        ),
    ]
