# Generated by Django 3.2.3 on 2021-09-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0005_auto_20210923_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nebula',
            name='Max',
        ),
        migrations.RemoveField(
            model_name='nebula',
            name='Min',
        ),
        migrations.AddField(
            model_name='nebula',
            name='Name your Nebula',
            field=models.CharField(default='System BC87', max_length=100),
        ),
    ]
