# Generated by Django 3.2.3 on 2021-09-24 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0003_auto_20210923_0254'),
        ('space', '0006_auto_20210923_2257'),
    ]

    operations = [
    ]
